version: "3.8"
services:
  keycloak:
    container_name: keycloak
    command:
      - " -b 0.0.0.0"
      - " -Djboss.socket.binding.port-offset=1"
    image: uptocloudregister.azurecr.io/keycloak
    restart: always
    volumes: 
      - ${WEBAPP_STORAGE_HOME}/imports/keycloak/realm-export.json:/keycloak/realm-export.json
      - ${WEBAPP_STORAGE_HOME}/imports/certs/tls.crt:/etc/x509/https/tls.crt
      - ${WEBAPP_STORAGE_HOME}/imports/certs/tls.key:/etc/x509/https/tls.key
    environment:
      KEYCLOAK_USER: postgres
      KEYCLOAK_PASSWORD: adminuptocloud
      KEYCLOAK_IMPORT: /keycloak/realm-export.json
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: uptoclouddb
      KEYCLOAK_DATABASE_NAME: keycloakdb
      DB_VENDOR: h2
  db:
    container_name: db
    image: uptocloudregister.azurecr.io/postgres
    restart: always
    environment:
      POSTGRES_DB: uptoclouddb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: uptoclouddb
    volumes:
      - ${WEBAPP_STORAGE_HOME}/imports/db/uptoclouddb.sql:/docker-entrypoint-initdb.d/uptoclouddb.sql  
  
  springbootapp:
    depends_on:
      - db
      - keycloak
    container_name: springbootapp
    image: uptocloudregister.azurecr.io/springbootapp
    restart: always

  frontend:
    depends_on:
      - db
      - keycloak
      - springbootapp
    container_name: frontend
    image: uptocloudregister.azurecr.io/frontend
    restart: always
    ports:
      - 80:80